const $=id=>document.getElementById(id);
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let workbook=null,parsed={rows:[],headers:[]},now=Date.now(),page=1,view='tracked',filtered=[],demoMode=false;
const pageSize=30;
const views={tracked:'待关闭',overdue:'已超 72 小时',missing:'未填完成时间',grace:'72 小时内暂缓',invalid:'待核实',closed:'已关闭 / 已取消',all:'全部记录'};
const fmt=(t)=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(t);
const num=n=>n.toLocaleString('zh-CN');
const matches=(r,v)=>v==='all'||(v==='tracked'?['overdue','missing'].includes(r.kind):r.kind===v);
function options(id,values,label,preserve=true){const current=preserve?$(id).value:'';$(id).innerHTML='<option value="">'+label+'</option>'+values.map(v=>'<option value="'+escapeHTML(v)+'">'+escapeHTML(v)+'</option>').join('');if(values.includes(current))$(id).value=current;}
function baseRows(skipRegion=false){const q=$('search').value.trim().toLowerCase();return parsed.rows.filter(r=>(skipRegion||(!$('region').value||r.region===$('region').value)&&(!$('sub').value||r.sub===$('sub').value))&&['country','status','owner','type','priority'].every(k=>!$(k).value||r[k]===$(k).value)&&(!q||Object.keys(WO.columns([])).some(k=>String(r[k]??'').toLowerCase().includes(q))));}
function updateSub(){const b=$('region').value;options('sub',[...new Set(parsed.rows.filter(r=>!b||r.region===b).map(r=>r.sub))].sort(),'全部子区域');}
function reset(){['search','region','sub','country','status','owner','type','priority'].forEach(k=>$(k).value='');$('sort').value='oldest';view='tracked';page=1;updateSub();render();}
function render(){
  now=Date.now();$('asof').textContent=fmt(now)+' 北京时间';parsed.rows.forEach(r=>{r.kind=WO.classify(r,now);r.hours=Number.isFinite(r.completeMs)&&r.completeMs!==null?(now-r.completeMs)/3600000:null;});
  const base=baseRows();const count=v=>base.filter(r=>matches(r,v)).length;
  $('metrics').innerHTML=[['待关闭工单',count('tracked'),'已超 72 小时 + 未填完成时间','primary'],['已超 72 小时',count('overdue'),'服务已完成，等待关闭',''],['未填完成时间',count('missing'),'需跟进服务进展或补齐时间',''],['72 小时内暂缓',count('grace'),'尚在处理窗口，不计入待关闭','']].map(([label,n,hint,cls])=>'<div class="metric '+cls+'"><div class="label">'+label+'</div><div class="num">'+(parsed.rows.length?num(n):'—')+'</div><div class="hint">'+hint+'</div></div>').join('');
  const regional=baseRows(true).filter(r=>matches(r,'tracked'));const regions=[...Object.keys(WO.REGIONS),...(parsed.rows.some(r=>r.region==='未匹配')?['未匹配']:[])];const max=Math.max(1,...regions.map(k=>regional.filter(r=>r.region===k).length));
  $('regions').innerHTML=regions.map(k=>{const rs=regional.filter(r=>r.region===k),over=rs.filter(r=>r.kind==='overdue').length;return '<button class="region-card '+($('region').value===k?'active':'')+'" data-region="'+k+'"><span class="region-name">'+k+'</span><b>'+ (parsed.rows.length?num(rs.length):'—')+'</b><small>待关闭</small><div class="bar"><i style="width:'+rs.length/max*100+'%"></i></div><small>超 72h <strong>'+over+'</strong></small></button>';}).join('');
  $('tabs').innerHTML=Object.entries(views).map(([key,label])=>'<button class="tab '+(view===key?'active':'')+'" aria-pressed="'+(view===key)+'" data-view="'+key+'">'+label+'<span>'+num(count(key))+'</span></button>').join('');
  filtered=base.filter(r=>matches(r,view)).sort((a,b)=>{if($('sort').value==='id')return a.id.localeCompare(b.id);const at=Number.isFinite(a.completeMs)&&a.completeMs!==null?a.completeMs:null,bt=Number.isFinite(b.completeMs)&&b.completeMs!==null?b.completeMs:null;if(at===null)return bt===null?a.row-b.row:1;if(bt===null)return -1;return $('sort').value==='oldest'?at-bt:bt-at;});
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,pages);
  $('resultcount').textContent=parsed.rows.length?views[view]+' · '+num(filtered.length)+' 条'+(demoMode?' · 演示数据':''):'等待导入工单表格';
  $('tbody').innerHTML=filtered.length?filtered.slice((page-1)*pageSize,page*pageSize).map(r=>'<tr><td><button class="id-link" data-row="'+r.row+'">'+escapeHTML(r.id||'未填写编号 · 行 '+r.row)+'</button><small title="'+escapeHTML(r.account)+'">'+escapeHTML(r.account||'—')+'</small></td><td>'+escapeHTML(r.region)+'<small>'+escapeHTML(r.sub)+'</small></td><td>'+escapeHTML(r.country||'—')+'</td><td><span class="badge">'+escapeHTML(r.status||'未填写')+'</span></td><td>'+escapeHTML(r.complete||'未填写')+'</td><td class="'+(r.kind==='overdue'?'age':'missing')+'">'+age(r)+'</td><td>'+escapeHTML(r.owner||'—')+'</td><td>'+escapeHTML(r.priority||'—')+'</td></tr>').join(''):'<tr><td colspan="8" class="empty">'+(parsed.rows.length?'当前条件下没有工单<br>可切换分类或重置筛选':'导入工单 Excel，开始追踪<br>数据仅在当前浏览器中处理')+'</td></tr>';
  $('pageinfo').textContent='第 '+page+' / '+pages+' 页 · 每页 '+pageSize+' 条';$('prev').disabled=page<=1;$('next').disabled=page>=pages;$('export').disabled=!filtered.length;
}
function age(r){if(r.kind==='closed')return '已排除';if(r.kind==='invalid')return '待核实';if(r.hours===null)return '未填完成时间';return Math.floor(r.hours/24)+' 天 '+Math.floor(r.hours%24)+' 小时';}
function adopt(result){parsed=result;const msgs=[];if(result.duplicate)msgs.push(result.duplicate+' 条重复工单号已保留，请核对，数量按行计算');if(result.blankId)msgs.push(result.blankId+' 条缺少工单号');const issues=parsed.rows.filter(r=>r.regionIssue).length;if(issues)msgs.push(issues+' 条区域信息缺失或与映射不一致（已优先按子区域映射）');const invalid=parsed.rows.filter(r=>WO.classify(r,Date.now())==='invalid').length;if(invalid)msgs.push(invalid+' 条时间或工单状态异常，已放入“待核实”');$('message').textContent=msgs.join('；');options('region',[...Object.keys(WO.REGIONS),...(parsed.rows.some(r=>r.region==='未匹配')?['未匹配']:[])],'全部大区',false);['country','status','owner','type','priority'].forEach(k=>options(k,[...new Set(parsed.rows.map(r=>r[k]).filter(Boolean))].sort(),'全部',false));reset();$('filemeta').textContent=(demoMode?'演示数据 · ':'')+num(parsed.rows.length)+' 条记录 · '+(parsed.headers.length)+' 个字段 · 本地处理';}
function parseSheet(){if(!workbook)return;try{const matrix=XLSX.utils.sheet_to_json(workbook.Sheets[$('sheet').value],{header:1,defval:'',raw:true});adopt(WO.parse(matrix,{offset:Number($('timezone').value),date1904:!!workbook.Workbook?.WBProps?.date1904}));}catch(e){parsed={rows:[],headers:[]};reset();$('message').textContent=e.message;$('filemeta').textContent='当前工作表无法生成看板，请选择其他工作表或重新导入。';}}
async function importFile(file){if(!file)return;if(!/\.(xlsx|xls|csv)$/i.test(file.name)){$('message').textContent='请选择 .xlsx、.xls 或 .csv 文件。';return;}if(file.size>40*1024*1024){$('message').textContent='文件超过 40 MB，请缩小导出范围后再导入。';return;}$('message').textContent='正在读取表格…';try{if(typeof XLSX==='undefined')throw Error('Excel 解析组件未加载，请确认 vendor 文件夹完整。');const next=XLSX.read(await file.arrayBuffer(),{type:'array',nodim:true});const names=next.SheetNames.filter((n,i)=>!next.Workbook?.Sheets?.[i]?.Hidden);if(!names.length)throw Error('没有可读取的可见工作表。');workbook=next;demoMode=false;$('filename').textContent=file.name;options('sheet',names,'请选择工作表',false);$('sheet').value=names.find(n=>{try{WO.parse(XLSX.utils.sheet_to_json(next.Sheets[n],{header:1,defval:''}));return true;}catch{return false;}})||names[0];$('sheet').disabled=false;parseSheet();}catch(e){$('message').textContent='导入失败：'+e.message;}finally{$('file').value='';}}
$('file').addEventListener('change',e=>importFile(e.target.files[0]));
['dragenter','dragover'].forEach(ev=>$('dropzone').addEventListener(ev,e=>{e.preventDefault();$('dropzone').classList.add('drag');}));['dragleave','drop'].forEach(ev=>$('dropzone').addEventListener(ev,e=>{e.preventDefault();$('dropzone').classList.remove('drag');}));$('dropzone').addEventListener('drop',e=>importFile(e.dataTransfer.files[0]));
$('sheet').onchange=parseSheet;$('timezone').onchange=()=>{if(demoMode)loadDemo();else parseSheet();};$('refresh').onclick=render;$('reset').onclick=reset;
['region','sub','country','status','owner','type','priority','sort'].forEach(k=>$(k).onchange=()=>{if(k==='region'){ $('sub').value='';updateSub();}page=1;render();});$('search').oninput=()=>{page=1;render();};
$('regions').onclick=e=>{const b=e.target.closest('[data-region]');if(!b)return;$('region').value=$('region').value===b.dataset.region?'':b.dataset.region;$('sub').value='';updateSub();page=1;render();};
$('tabs').onclick=e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;page=1;render();}};
$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
$('tbody').onclick=e=>{const b=e.target.closest('[data-row]');if(!b)return;const r=parsed.rows.find(r=>r.row===Number(b.dataset.row));$('detail-content').innerHTML='<dl><dt>统计分类</dt><dd>'+views[r.kind]+'</dd><dt>标准化大区 / 子区域</dt><dd>'+escapeHTML(r.region+' / '+r.sub)+'</dd>'+parsed.headers.map((h,i)=>'<dt>'+escapeHTML(h)+'</dt><dd>'+escapeHTML(r.raw[i]||'—')+'</dd>').join('')+'</dl>';$('detail').showModal();};$('close-detail').onclick=()=>$('detail').close();
$('export').onclick=()=>{const headers=['工单编号','大区','子区域','国家','客户','工单状态','Service Complete Time','统计分类','负责人','优先级','原表行号','统计时点（北京时间）'];const matrix=[headers,...filtered.map(r=>[r.id,r.region,r.sub,r.country,r.account,r.status,r.complete,views[r.kind],r.owner,r.priority,r.row,fmt(now)])];const out=XLSX.utils.book_new();XLSX.utils.book_append_sheet(out,XLSX.utils.aoa_to_sheet(matrix),'筛选结果');XLSX.writeFile(out,'工单追踪_'+views[view].replaceAll('/','-')+'_'+new Date().toISOString().slice(0,10)+'.xlsx');};
function loadDemo(){demoMode=true;workbook=null;$('sheet').innerHTML='<option>演示数据</option>';$('sheet').disabled=true;$('filename').textContent='演示数据 · 不包含真实工单';const headers=['Work Order Number','Service Sales Region','Service Region','Work Order Status','Service Complete Time','Country','Owner','Account Name','Priority','Work Order Type'];const matrix=[headers];const local=(t)=>new Date(t+Number($('timezone').value)*3600000).toISOString().slice(0,19).replace('T',' ');Object.entries(WO.REGIONS).forEach(([b,subs],bi)=>{for(let i=0;i<14+bi*3;i++){matrix.push(['DEMO-'+b+'-'+String(i+1).padStart(3,'0'),b,subs[i%subs.length],i===0?'Closed':'In Progress',i%4===0?'':local(Date.now()-(i%5===0?30:100+i*19)*3600000),['示例国家 A','示例国家 B'][i%2],'负责人 '+(i%4+1),'示例客户 '+(i+1),i%3?'Generally':'Urgent','Repair']);}});adopt(WO.parse(matrix,{offset:Number($('timezone').value)}));}
$('demo').onclick=loadDemo;$('method').innerHTML='<div class="mapping">'+Object.entries(WO.REGIONS).map(([k,v])=>'<span><strong>'+k+'</strong> · '+v.join(' / ')+'</span>').join('')+'</div><p>Korea → KOR；RCIS 子区域 → CIS。优先使用子区域映射大区；无法识别子区域时保留有效的原始大区，无法匹配的大区单列。</p>';
['region','sub','country','status','owner','type','priority'].forEach(k=>options(k,[],'全部'));render();setInterval(render,60000);
